version: "3.8"
name: "user-system"

services:
  postgres:
    image: postgres:15
    container_name: postgres-user-system
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis-user-system
    ports:
      - "6379:6379"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus-user-system
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service-user-system
    ports:
      - "${AUTH_SERVICE_PORT}:8081"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AUTH_SERVICE_PORT: ${AUTH_SERVICE_PORT}
      SPRING_DATASOURCE_URL: ${AUTH_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
      JWT_EXPIRY: ${JWT_EXPIRY}
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ./logs:/logs
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
    container_name: user-service-user-system
    ports:
      - "${USER_SERVICE_PORT}:8082"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      SPRING_DATASOURCE_URL: ${USER_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
      JWT_EXPIRY: ${JWT_EXPIRY}
    volumes:
      - ./logs:/logs
    restart: unless-stopped

volumes:
  postgres_data:
