version: "3.8"
name: "user-system"

services:
  postgres:
    image: postgres:15
    container_name: postgres-user-system
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service-user-system
    ports:
      - "${AUTH_SERVICE_PORT}:8081"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${AUTH_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
    container_name: user-service-user-system
    ports:
      - "${USER_SERVICE_PORT}:8082"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${USER_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    restart: unless-stopped

volumes:
  postgres_data:
