global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: /auth/actuator/prometheus
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'user-service'
    metrics_path: /user/actuator/prometheus
    static_configs:
      - targets: ['user-service:8082']
