spring:
  config:
    activate:
      on-profile: test
  
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_service_db}
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:Abc123}
#
#  jpa:
#    hibernate:
#      ddl-auto: false
#    show-sql: none