#server:
#  port: 8082
#  servlet:
#    context-path: /user

spring:
  application:
    name: user-service

  profiles:
    active: dev

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_service_db}
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:Abc123}
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: qxDRHYT3pRMIJkG7pFsaUkbSkFr3+X3hi3n1ci64B7mAS7RH+Ws4V0ao/nHyyBgGWZY2FpEKCgTXNUpf79t2Tw==
